channels:
  - defaults
  - cadquery
  - conda-forge
dependencies:
  - python=3.8
  - pip=21.0
  - cadquery=master
  - matplotlib=3.3
  - xorg-libxcursor
  - xorg-libxft
  - xorg-libxinerama
  - pip:
      - jupyter-cadquery==3.1.0rc3
