channels:
  - defaults
  - cadquery
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - cadquery=master
  - pip:
      - jupyter-cadquery==3.0.0
      - gmsh
      - pmef
      - scipy
      - pyvista
      - meshio
      - ipywidgets
      - pythreejs
